#!/bin/bash

# This script downloads and installs oscpack 1.1.0 to /usr/local

rm -f oscpack_1_1_0.zip
rm -rf  oscpack_1_1_0
sudo rm -rf /usr/local/include/oscpack
sudo rm -f /usr/local/lib/liboscpack.a 

wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/oscpack/oscpack_1_1_0.zip
unzip oscpack_1_1_0.zip
rm -f oscpack_1_1_0.zip
cd oscpack_1_1_0
mkdir build
cd build
cmake ..
make
sudo cp liboscpack.a /usr/local/lib
cd ..
sudo mkdir /usr/local/include/oscpack
sudo mkdir /usr/local/include/oscpack/osc
sudo mkdir /usr/local/include/oscpack/ip
sudo cp osc/*.h /usr/local/include/oscpack/osc
sudo cp ip/*.h /usr/local/include/oscpack/ip
