#!/bin/bash

printf "amSynth currently contains "

wc -l `find | grep 'cc'$` `find | grep '\.h'$` | grep 'total' | sed -e 's/total//' \
	| tr '\n' '\0' | tr ' ' '\0'

printf " lines of code in "

du -s `find | grep '\.h'$` `find | grep '\.cc'$` | wc -l \
	| tr '\n' '\0' | tr ' ' '\0'

printf " source files.\n"
