.TH AMSYNTH "1" "Septembre 2016" "amsynth 1.6.4" "Commandes utilisateur"
.SH NOM
amsynth \- un synthétiseur logiciel à deux oscillateurs.
.SH SYNOPSIS
.PP
.B amsynth
[options]
.SH DESCRIPTION
.PP
amsynth 1.6.4 [Janv 19 2016]  [http://amsynth.github.io/].
Copyright 2001\-2016 Nick Dowell <nixx@nixx.org.uk>.
.PP
amsynth est un synthétiseur logiciel facile à utiliser avec une topologie de synthétiseur soustractif classique.
.PP
amsynth est fourni SANS AUCUNE GARANTIE.
C'est un logiciel libre, et vous êtes encouragé à le redistribuer sous certaines conditions.
Voir le fichier COPYING pour les détails.
.SH OPTIONS
.PP
Toute option donnée ici écrase celle du fichier de configuration ($HOME/.amSynthrc).
.HP
\fB\-h\fR \- affiche un message d'aide (en anglais)
.HP
\fB\-v\fR \- affiche les informations de version
.HP
\fB\-b\fR <nom_de_fichier> \- utilise <nom_de_fichier> en tant que banque pour sauvegarder les pré-réglages
.HP
\fB\-t\fR <nom_de_fichier> \- utilise <nom_de_fichier> en tant que fichier d'accordage
.HP
\fB\-a\fR <chaîne_de_caractères> \- paramètre le pilote de sortie son à utiliser [alsa/oss/auto(défaut)]
.HP
\fB\-r\fR <entier> \- paramètre le taux d'échantillonnage à utiliser
.HP
\fB\-m\fR <chaîne_de_caractères> \- paramètre le pilote MIDI à utiliser [alsa/oss/auto(défaut)]
.HP
\fB\-c\fR <chaîne_de_caractères> \- paramètre le canal MIDI auquel répondre (défaut=tous)
.HP
\fB\-p\fR <entier> \- paramètre la polyphonie (voix actives maximum)
.HP
\fB\-n\fR <nom> \- spécifie le nom de client JACK à utiliser
.HP
\fB\-\-jack_autoconnect=<true|false>
.SH FICHIERS
.TP
.B $HOME/.amSynthrc
.PP
Configuration pour amsynth.
.TP
.B $HOME/.amsynth/*
.PP
Banques et autres.
.TP
.B $HOME/.amSynth.presets
.PP
Pré-réglages.
.SH ENVIRONEMENT
.PP
nothing
.SH BOGUES & DEMANDE DE FONCTIONNALITÉS
.PP
Si vous trouvez un bogue, ou si vous voulez proposer une nouvelle fonctionnalité, veuillez le reporter à https://github.com/amsynth/amsynth/issues .
.SH AUTEURS
.PP
Nick Dowell et contributeurs. Voir la liste complète dans le dialogue d'amsynth : "Aide" -> "À propos".
.SH DIVERS
Cette page de manuel a été écrite par Olivier Humbert <trebmuh@tuxfamily.org> le 06 septembre 2016 en tant que partie du projet LibraZiK (et peut être utilisé par d'autres).
