name: Linux

on:
  push:
    paths-ignore:
      - '.github/workflows/mac.yml'
      - '.github/workflows/windows.yml'
      - '.gitignore'
      - 'mac/**'
      - 'src/plugins/au/**'
      - 'win/**'

jobs:
  build:
    runs-on: ubuntu-${{ matrix.release }}
    strategy:
      matrix:
        include:
          - release: 22.04
          - release: 24.04
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 2
    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install autopoint dssi-dev intltool libasound-dev libcurl4-openssl-dev libfreetype-dev libjack-jackd2-dev liblo-dev libpng-dev libxcursor-dev libxinerama-dev libxrandr-dev pandoc
    - run: ./autogen.sh
    - run: ./configure --enable-compile-warnings=error --without-lash
    - run: make -j 2 distcheck
    - run: make -j 2
    - name: Run make install
      run: sudo make install
#    - run: ./tools/lv2lint.sh # lv2lint seems to have disappeared from the internet
    - name: Run make check
      run: |
        ./configure CFLAGS='-O0 -g -fprofile-arcs -ftest-coverage' --without-lv2 --without-dssi --without-vst --without-gui --without-lash
        make -j 2 check
    - name: Run gcov
      run: gcov -lp $(find . -name '*.c' -o -name '*.cpp')
      if: matrix.release == '22.04'
    - uses: codecov/codecov-action@v7
      if: matrix.release == '22.04'
    - uses: actions/upload-artifact@v7
      if: matrix.release == '22.04'
      with:
        name: amsynth-tarball-${{ github.sha }}
        path: amsynth-*.tar.gz
